version: '3.8'

services:
  app:
    build:
      context: ./backend # Указывает на директорию с Dockerfile
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  front:
    build:
      context: ./frontend # Указывает на директорию с Dockerfile
      dockerfile: Dockerfile
    ports:
      - "80:80" # Маппинг порта: локальный порт 80 к порту 80 контейнера
    volumes:
      - /usr/src/front/node_modules

volumes:
  mongodb_data: