module.exports.STATUS_CODE_CREATED = 201;
module.exports.STATUS_CODE_BAD_REQUEST = 400;
module.exports.STATUS_CODE_UNAUTHORIZED = 401;
module.exports.STATUS_CODE_FORBIDDEN = 403;
module.exports.STATUS_CODE_NOT_FOUND = 404;
module.exports.STATUS_CODE_CONFLICT = 409;
module.exports.STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
